name: social_network_flutter
description: Opensource social network

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^3.25.0
  flutter_svg: ^0.20.0-nullsafety.3
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  google_fonts: ^1.1.1
  cupertino_icons: ^1.0.0
  flutter_custom_clippers: ^1.1.2
  crypto: ^2.1.5
  photo_manager: ^0.5.8
  photo_view: ^0.10.3
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

